### ISSUE TITLE
DSR and Ancillary services

### ISSUE THREAD

**Issue by desenk** [desenk/Impact-of-COVID-19-Lockdown-on-Electricity-Demand-in-GB#10]
*Check if data is avaiable (volume,date,pricing) [Max,Desen]
*i.e. STOR data, number of voltage measure [Max,Desen]
*Catch up on Friday. Set time [Max]

**Comment by pz-max** [comment]
@desenk 
I found the following:
1. Data on BM market:
a) BM market activity. Where we can see if units were activated  (DSR, STOR, etc. get scheduled)
[https://www2.bmreports.com/bmrs/?q=balancing/marketactivity/](url)
b) For the BM market activity a register exists, which contains more data:
[https://www.elexonportal.co.uk/category/view/180?cachebust=5xa3urmtd1](url)
With a) and b) both we could see that DSR services were more often activated..

2) Inertia is measured by NationalGrid and showed in the control room. However, no data set was found. [https://www.current-news.co.uk/news/uk-grid-stability-continuously-measured-for-the-first-time](url)

3) Nothing more on Ancillary service

**Comment by desenk** [comment]
Too much confusion about this. We can ask Aristides and re-open the issue.
