### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by desenk** [desenk/Impact-of-COVID-19-Lockdown-on-Electricity-Demand-in-GB#14]
*Bring all together, Summarize how all changed, and add speculation
*Draft [Wait till results, Des+Max]
*Thoughts about a summary table [Max]
* Give advice to audience and judge pricing schemes [Des,Max]
*use of IoT, smart meters, controller - load coordination, smart contracts, agile pricing [Des]

**Comment by pz-max** [comment]
Added a summary table. Think it would be useful for readers who just want to see if there is something they didn't expect. 
As final Table, I would recommend inserting a Word/PPT Table as they are far more beautiful (or we can adjust the Latex table to make it as appealing.

**Comment by pz-max** [comment]
Drafted a discussion. We should implement:
1) Limitations
2) Recommendations (Maybe emphasizing some work of AGILE Group and also sharing some love to great work of others ((i.e. research that improves grid stability, such as inertia from VRE, resilience analysis, etc.)
3) Tomorrow I make a fancy result summary "figure" - best idea of the day Desen! 🥇
