### ISSUE TITLE
Conclusions

### ISSUE THREAD

**Issue by desenk** [desenk/Impact-of-COVID-19-Lockdown-on-Electricity-Demand-in-GB#16]
*copy from intro
*summarise contributions
***This paper encourage further research***

**Comment by pz-max** [comment]
Just a note: The conclusion could be dropped if adding no value and all points can be smoothly built-in discussion.

That's also welcome by Journal Energies:
"The CONCLUSION section is not mandatory but can be added to the manuscript if the discussion is unusually long or complex."
