### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by desenk** [desenk/Impact-of-COVID-19-Lockdown-on-Electricity-Demand-in-GB#9]
*Make this a subsection of "Forecasting + Grid Stability indicators"
*Histogram updated [Des]
*Make bullet point for Max to populate this text [Des]
*respond to Feedback Loop [Max]

**Comment by pz-max** [comment]
@desenk  Prio 2. Think I had problems with interpreting the Histogram and the peak 2 ratio. Wasn't sure if the Figure shows significant changes. Maybe you find a way to interpret it?

So far I wrote about 2 things in the section:
1. Frequency is still stable
2. Higher VRE share lead to general lower inertia and make the system in general more prone for rapid frequency changes
